name: build and push

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKERIO_PASSWORD }}" | docker login -u "${{ secrets.DOCKERIO_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          VERSION=`cat VERSION`
          LATESTVERSION=`curl https://raw.githubusercontent.com/jcmendez/hass-configurator-docker/master/VERSION`
          TAGS="--tag jcmendez/hass-configurator-docker:$VERSION "
          if [ $VERSION == $LATESTVERSION ]; then
            TAGS="$TAGS --tag jcmendez/hass-configurator-docker:latest"
          fi
          docker buildx build --push \
            --build-arg HC_BUILD_VERSION=$VERSION \
            $TAGS \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .